
### GET ALL Products

GET http://localhost:4000/products

### GET Product by ids

GET http://localhost:4000/products?ids=4&ids=3

### GET Product by id

GET http://localhost:4000/products/3

### POST Products

POST http://localhost:4000/products
Content-Type: application/json

{
  "name": "Beef",
  "manufacturer": "Costco",
  "country": "USA",
  "unitPrice": 300
}

### PUT Product

PUT http://localhost:4000/products/1
Content-Type: application/json

{
  "country": "China"
}


### DELETE Product

DELETE http://localhost:4000/products/2