
### GET ALL Products

GET http://localhost:4000/products

### GET Product by id

GET http://localhost:4000/products/3

### POST Products

POST http://localhost:4000/products
Content-Type: application/json

{
  "name": "Watch",
  "manufacturer": "Apple",
  "country": "USA",
  "unitPrice": 800
}

### PUT Product

PUT http://localhost:4000/products/1
Content-Type: application/json

{
  "country": "China"
}


### DELETE Product

DELETE http://localhost:4000/products/2